package workflow

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/google/uuid"

	"github.com/komi/komi/backend-go/internal/session"
)

// ExecutionStore is the read-only subset required to execute a published
// workflow. Keeping it separate from Store avoids coupling workflow execution
// to editor-only operations.
type ExecutionStore interface {
	Get(ctx context.Context, workflowID, organizationID uuid.UUID) (*Workflow, error)
	GetNodes(ctx context.Context, workflowID, organizationID uuid.UUID) (*NodesResult, error)
}

type ExecutionResult struct {
	Success              bool
	Message              string
	NextNodeID           *uuid.UUID
	State                map[string]any
	ShouldContinue       bool
	TransferToHuman      bool
	TransferGroupID      string
	TransferReason       string
	TransferDescription  string
	EndChat              bool
	EndChatReason        string
	EndChatDescription   string
	RequestRating        bool
	RequestContact       bool
	Error                string
	FormData             map[string]any
	LandingPageData      map[string]any
	IntermediateMessages []string
}

type Executor struct {
	workflows  ExecutionStore
	sessions   session.WorkflowStore
	complete   CompletionProvider
	hasHistory HistoryProvider
}

// LLMReply is the subset of the structured agent reply that a workflow is
// allowed to act on. It intentionally mirrors the Python workflow agent
// contract instead of treating model JSON as display text.
type LLMReply struct {
	Message             string `json:"message"`
	TransferToHuman     bool   `json:"transfer_to_human"`
	TransferReason      string `json:"transfer_reason"`
	TransferDescription string `json:"transfer_description"`
	EndChat             bool   `json:"end_chat"`
	EndChatReason       string `json:"end_chat_reason"`
	EndChatDescription  string `json:"end_chat_description"`
	RequestRating       bool   `json:"request_rating"`
}

type CompletionProvider func(ctx context.Context, model, systemPrompt, userMessage string) (LLMReply, error)
type HistoryProvider func(ctx context.Context, sessionID, organizationID uuid.UUID) bool

// ParseLLMReply keeps non-JSON provider output usable while accepting the
// structured response generated by the shared chat-agent prompt.
func ParseLLMReply(raw string) LLMReply {
	var reply LLMReply
	if json.Unmarshal([]byte(raw), &reply) != nil {
		reply.Message = strings.TrimSpace(raw)
	}
	return reply
}

func NewExecutor(workflows ExecutionStore, sessions session.WorkflowStore) *Executor {
	return &Executor{workflows: workflows, sessions: sessions}
}

func NewExecutorWithCompletion(workflows ExecutionStore, sessions session.WorkflowStore, complete CompletionProvider) *Executor {
	return &Executor{workflows: workflows, sessions: sessions, complete: complete}
}

func NewExecutorWithProviders(workflows ExecutionStore, sessions session.WorkflowStore, complete CompletionProvider, hasHistory HistoryProvider) *Executor {
	return &Executor{workflows: workflows, sessions: sessions, complete: complete, hasHistory: hasHistory}
}

func (e *Executor) Execute(ctx context.Context, sessionID, organizationID, workflowID uuid.UUID, currentNodeID *uuid.UUID, state map[string]any, userMessage string) (*ExecutionResult, error) {
	if e == nil || e.workflows == nil || e.sessions == nil {
		return nil, errors.New("workflow execution service is not configured")
	}
	flow, err := e.workflows.Get(ctx, workflowID, organizationID)
	if err != nil || flow == nil {
		return nil, firstExecutionError(err, "workflow not found")
	}
	if !strings.EqualFold(flow.Status, "PUBLISHED") {
		return nil, errors.New("workflow is not published")
	}
	graph, err := e.workflows.GetNodes(ctx, workflowID, organizationID)
	if err != nil {
		return nil, err
	}
	if len(graph.Nodes) == 0 {
		return nil, errors.New("workflow has no nodes")
	}
	state = copyMap(state)
	if strings.TrimSpace(userMessage) != "" {
		state["user_message"] = userMessage
		variables, _ := state["variables"].(map[string]any)
		if variables == nil {
			variables = map[string]any{}
			state["variables"] = variables
		}
		variables["user_message"] = userMessage
	}
	nodes := make(map[uuid.UUID]Node, len(graph.Nodes))
	incoming := make(map[uuid.UUID]bool)
	outgoing := make(map[uuid.UUID][]Connection)
	for _, node := range graph.Nodes {
		nodes[node.ID] = node
	}
	for _, connection := range graph.Connections {
		incoming[connection.TargetNodeID] = true
		outgoing[connection.SourceNodeID] = append(outgoing[connection.SourceNodeID], connection)
	}
	for id := range outgoing {
		sort.SliceStable(outgoing[id], func(i, j int) bool { return outgoing[id][i].Priority < outgoing[id][j].Priority })
	}
	if currentNodeID == nil {
		for _, node := range graph.Nodes {
			if !incoming[node.ID] {
				id := node.ID
				currentNodeID = &id
				break
			}
		}
		if currentNodeID == nil {
			id := graph.Nodes[0].ID
			currentNodeID = &id
		}
	}
	result := &ExecutionResult{Success: true, State: state}
	for steps := 0; steps < 100; steps++ {
		node, ok := nodes[*currentNodeID]
		if !ok {
			return nil, errors.New("current workflow node was not found")
		}
		next := firstConnection(outgoing[node.ID])
		nodeType := strings.ToUpper(strings.TrimSpace(node.NodeType))
		switch nodeType {
		case "MESSAGE":
			message := interpolate(configStringDefault(node.Config, "message_text", ""), state)
			if message != "" {
				if next == nil {
					result.Message = message
				} else {
					result.IntermediateMessages = append(result.IntermediateMessages, message)
				}
			}
			if next == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := next.TargetNodeID
			currentNodeID = &id
		case "FORM":
			fields := configSlice(node.Config, "form_fields")
			if len(fields) == 0 {
				return nil, errors.New("form node has no fields")
			}
			if strings.EqualFold(stringFromMap(state, "form_state"), "submitted") {
				form := mapFromMap(state, "form_data")
				namedValues := make(map[string]any, len(form))
				for field, value := range form {
					namedValues[nodeVariableName(node, field)] = value
				}
				storeNodeVariables(state, node, namedValues)
				delete(state, "form_state")
				delete(state, "form_data")
				if err := e.sessions.AddWorkflowHistory(ctx, sessionID, organizationID, node.ID, "form_submission", form); err != nil {
					return nil, err
				}
				if next == nil {
					return e.finish(ctx, sessionID, organizationID, nil, result)
				}
				id := next.TargetNodeID
				currentNodeID = &id
				continue
			}
			form := map[string]any{"title": configString(node.Config, "form_title"), "description": configString(node.Config, "form_description"), "submit_button_text": configStringDefault(node.Config, "submit_button_text", "Submit"), "fields": fields, "form_full_screen": configBool(node.Config, "form_full_screen")}
			state["form_state"] = "waiting"
			result.FormData = form
			return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
		case "LANDING_PAGE":
			if strings.TrimSpace(userMessage) == "" {
				landing := map[string]any{"heading": interpolate(configStringDefault(node.Config, "landing_page_heading", "Welcome"), state), "content": interpolate(configStringDefault(node.Config, "landing_page_content", "Thank you for visiting!"), state)}
				result.LandingPageData = landing
				return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
			}
			if next == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := next.TargetNodeID
			currentNodeID = &id
		case "ACTION":
			result.IntermediateMessages = append(result.IntermediateMessages, "Action completed successfully.")
			if next == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := next.TargetNodeID
			currentNodeID = &id
		case "HUMAN_TRANSFER":
			transferRules := mapFromMap(node.Config, "transfer_rules")
			result.Message = interpolate(configStringDefault(transferRules, "message", configStringDefault(node.Config, "transfer_message", "Transferring you to a human agent. Please wait...")), state)
			result.TransferToHuman = true
			result.TransferGroupID = configStringDefault(node.Config, "transfer_group_id", configString(node.Config, "transfer_department"))
			result.TransferReason = configString(node.Config, "transfer_reason")
			result.TransferDescription = configString(node.Config, "transfer_description")
			return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
		case "WAIT":
			result.IntermediateMessages = append(result.IntermediateMessages, fmt.Sprintf("Please wait %s seconds...", configStringDefault(node.Config, "wait_duration", "0")))
			if next == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := next.TargetNodeID
			currentNodeID = &id
		case "END":
			result.Message = interpolate(configStringDefault(node.Config, "message_text", "Thank you for using our service!"), state)
			result.EndChat = true
			result.RequestRating = configBool(node.Config, "request_rating")
			result.EndChatReason = configString(node.Config, "end_chat_reason")
			result.EndChatDescription = configString(node.Config, "end_chat_description")
			return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
		case "USER_INPUT":
			if strings.TrimSpace(userMessage) == "" {
				result.Message = interpolate(configStringDefault(node.Config, "prompt_message", ""), state)
				state["user_input_state"] = "waiting"
				state["user_input_node_id"] = node.ID.String()
				return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
			}
			storeNodeVariables(state, node, map[string]any{nodeVariableName(node, "input"): strings.TrimSpace(userMessage)})
			delete(state, "user_input_state")
			delete(state, "user_input_node_id")
			if err := e.sessions.AddWorkflowHistory(ctx, sessionID, organizationID, node.ID, "user_input", map[string]any{"input": strings.TrimSpace(userMessage), "node_name": node.Name}); err != nil {
				return nil, err
			}
			if next == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := next.TargetNodeID
			currentNodeID = &id
		case "CONDITION":
			connection := selectCondition(outgoing[node.ID], interpolate(configString(node.Config, "condition_expression"), state), state)
			if connection == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := connection.TargetNodeID
			currentNodeID = &id
		case "LLM":
			if e.complete == nil {
				return nil, errors.New("LLM workflow provider is not configured")
			}
			if strings.TrimSpace(userMessage) == "" {
				userMessage = stringFromMap(state, "user_message")
			}
			exitCondition := strings.ToLower(strings.TrimSpace(configStringDefault(node.Config, "exit_condition", "single_execution")))
			continuous := exitCondition == "continuous_execution"
			if strings.TrimSpace(userMessage) == "" && !e.hasExecutionHistory(ctx, sessionID, organizationID, state) {
				if continuous {
					return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
				}
				if next == nil {
					return e.finish(ctx, sessionID, organizationID, nil, result)
				}
				id := next.TargetNodeID
				currentNodeID = &id
				continue
			}
			response, completeErr := e.complete(ctx, configString(node.Config, "model_id"), interpolate(configStringDefault(node.Config, "system_prompt", "You are a helpful customer service agent."), state), userMessage)
			if completeErr != nil {
				return nil, completeErr
			}
			result.Message = response.Message
			result.TransferReason = response.TransferReason
			result.TransferDescription = response.TransferDescription
			result.EndChat = response.EndChat
			result.EndChatReason = response.EndChatReason
			result.EndChatDescription = response.EndChatDescription
			result.RequestRating = response.RequestRating
			if continuous {
				result.TransferToHuman = response.TransferToHuman && configBool(node.Config, "auto_transfer_enabled")
				if result.TransferToHuman {
					result.TransferGroupID = configString(node.Config, "transfer_group_id")
					return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
				}
				if result.EndChat {
					if _, configured := node.Config["ask_for_rating"]; configured {
						result.RequestRating = configBool(node.Config, "ask_for_rating")
					} else {
						result.RequestRating = true
					}
					if next == nil {
						return e.finish(ctx, sessionID, organizationID, nil, result)
					}
					id := next.TargetNodeID
					return e.finish(ctx, sessionID, organizationID, &id, result)
				}
				return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
			}
			// single_execution always follows the graph after exactly one model
			// response. Transfer/end fields are meaningful only for continuous
			// nodes in the Python workflow contract.
			result.TransferToHuman = false
			result.EndChat = false
			result.RequestRating = false
			result.TransferReason = ""
			result.TransferDescription = ""
			result.EndChatReason = ""
			result.EndChatDescription = ""
			if next == nil {
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			if result.Message != "" {
				result.IntermediateMessages = append(result.IntermediateMessages, result.Message)
				result.Message = ""
			}
			id := next.TargetNodeID
			currentNodeID = &id
		case "GUARDRAILS":
			textToCheck := userMessage
			if strings.EqualFold(configStringDefault(node.Config, "text_source", "user_message"), "user_message") == false {
				source := configString(node.Config, "text_source")
				if !strings.HasPrefix(source, "{{") || !strings.HasSuffix(source, "}}") {
					source = "{{" + source + "}}"
				}
				textToCheck = interpolate(source, state)
			}
			if strings.TrimSpace(textToCheck) == "" {
				if next == nil {
					result.Message = "Content check passed successfully."
					return e.finish(ctx, sessionID, organizationID, nil, result)
				}
				id := next.TargetNodeID
				currentNodeID = &id
				continue
			}
			passed, checks, blockMessage := evaluateWorkflowGuardrails(textToCheck, node.Config)
			guards, _ := state["guardrails"].(map[string]any)
			if guards == nil {
				guards = map[string]any{}
				state["guardrails"] = guards
			}
			checked := textToCheck
			if len([]rune(checked)) > 100 {
				checked = string([]rune(checked)[:100]) + "..."
			}
			guards[node.ID.String()] = map[string]any{"passed": passed, "results": checks, "checked_text": checked}
			if !passed && strings.EqualFold(configStringDefault(node.Config, "pii_action", "block"), "redact") {
				for _, check := range checks {
					if redacted, ok := check["redacted_text"].(string); ok && redacted != "" {
						state["last_redacted_message"] = redacted
						break
					}
				}
			}
			connection := guardrailConnection(outgoing[node.ID], passed)
			if !passed && connection == nil {
				result.Message = configStringDefault(node.Config, "block_message", blockMessage)
				return e.finish(ctx, sessionID, organizationID, currentNodeID, result)
			}
			if connection == nil {
				result.Message = "Content check passed successfully."
				return e.finish(ctx, sessionID, organizationID, nil, result)
			}
			id := connection.TargetNodeID
			currentNodeID = &id
		default:
			return nil, fmt.Errorf("unsupported workflow node type %q", node.NodeType)
		}
		// A visitor message is consumed by the first node in an automatic run.
		// Subsequent nodes read explicitly persisted workflow variables, matching
		// the Python executor's per-iteration reset.
		userMessage = ""
	}
	return nil, errors.New("workflow exceeded maximum execution steps")
}

func (e *Executor) hasExecutionHistory(ctx context.Context, sessionID, organizationID uuid.UUID, state map[string]any) bool {
	if e.hasHistory != nil && e.hasHistory(ctx, sessionID, organizationID) {
		return true
	}
	return false
}

func (e *Executor) SubmitForm(ctx context.Context, sessionID, organizationID, workflowID uuid.UUID, currentNodeID *uuid.UUID, state, formData map[string]any) (*ExecutionResult, error) {
	if currentNodeID == nil {
		return nil, errors.New("workflow is not waiting for a form")
	}
	state = copyMap(state)
	if !strings.EqualFold(stringFromMap(state, "form_state"), "waiting") {
		return nil, errors.New("workflow is not waiting for a form")
	}
	state["form_state"] = "submitted"
	state["form_data"] = formData
	return e.Execute(ctx, sessionID, organizationID, workflowID, currentNodeID, state, "")
}

func (e *Executor) finish(ctx context.Context, sessionID, organizationID uuid.UUID, currentNodeID *uuid.UUID, result *ExecutionResult) (*ExecutionResult, error) {
	if ok, err := e.sessions.SetWorkflowState(ctx, sessionID, organizationID, currentNodeID, result.State); err != nil {
		return nil, err
	} else if !ok {
		return nil, errors.New("workflow session was not found")
	}
	result.ShouldContinue = result.NextNodeID != nil && !result.TransferToHuman && !result.EndChat && result.FormData == nil && result.LandingPageData == nil
	return result, nil
}

func ValidateForm(fields []any, values map[string]any) []string {
	errorsFound := make([]string, 0)
	for _, raw := range fields {
		field, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		name := strings.TrimSpace(fmt.Sprint(field["name"]))
		if name == "" {
			name = strings.TrimSpace(fmt.Sprint(field["id"]))
		}
		if name == "" {
			continue
		}
		value := strings.TrimSpace(fmt.Sprint(values[name]))
		if required, _ := field["required"].(bool); required && value == "" {
			errorsFound = append(errorsFound, name+" is required")
			continue
		}
		if value != "" && strings.EqualFold(fmt.Sprint(field["type"]), "email") && !emailPattern.MatchString(value) {
			errorsFound = append(errorsFound, name+" must be a valid email address")
		}
	}
	return errorsFound
}

var interpolationPattern = regexp.MustCompile(`\{\{\s*([^{}]+?)\s*\}\}`)
var emailPattern = regexp.MustCompile(`^[^\s@]+@[^\s@]+\.[^\s@]+$`)

func interpolate(value string, state map[string]any) string {
	return interpolationPattern.ReplaceAllStringFunc(value, func(match string) string {
		key := strings.TrimSpace(interpolationPattern.FindStringSubmatch(match)[1])
		if key == "user_message" {
			if value := stringFromMap(state, key); value != "" {
				return value
			}
			if variables, ok := state["variables"].(map[string]any); ok {
				return fmt.Sprint(variables[key])
			}
			return ""
		}
		parts := strings.SplitN(key, ".", 2)
		variables, _ := state["variables"].(map[string]any)
		if len(parts) == 2 {
			if node, ok := variables[parts[0]].(map[string]any); ok {
				return fmt.Sprint(node[parts[1]])
			}
			return ""
		}
		for _, raw := range variables {
			if node, ok := raw.(map[string]any); ok {
				if value, exists := node[key]; exists {
					return fmt.Sprint(value)
				}
			}
		}
		return ""
	})
}

func firstConnection(connections []Connection) *Connection {
	if len(connections) == 0 {
		return nil
	}
	return &connections[0]
}
func copyMap(value map[string]any) map[string]any {
	result := map[string]any{}
	for key, item := range value {
		result[key] = item
	}
	return result
}
func stringFromMap(value map[string]any, key string) string {
	if text, ok := value[key].(string); ok {
		return text
	}
	return ""
}
func mapFromMap(value map[string]any, key string) map[string]any {
	if found, ok := value[key].(map[string]any); ok {
		return found
	}
	return map[string]any{}
}
func configString(config map[string]any, key string) string { return stringFromMap(config, key) }
func configStringDefault(config map[string]any, key, fallback string) string {
	if value := configString(config, key); value != "" {
		return value
	}
	return fallback
}
func configBool(config map[string]any, key string) bool { value, _ := config[key].(bool); return value }
func configSlice(config map[string]any, key string) []any {
	value, _ := config[key].([]any)
	return value
}
func storeFormVariables(state map[string]any, nodeID uuid.UUID, values map[string]any) {
	variables, _ := state["variables"].(map[string]any)
	if variables == nil {
		variables = map[string]any{}
		state["variables"] = variables
	}
	variables[nodeID.String()] = values
}

func storeNodeVariables(state map[string]any, node Node, values map[string]any) {
	storeFormVariables(state, node.ID, values)
}

func nodeVariableName(node Node, suffix string) string {
	name := strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(node.Name, " ", "_"), "-", "_"))
	name = regexp.MustCompile(`[^a-z0-9_]`).ReplaceAllString(name, "")
	if name == "" {
		name = "user_input"
	}
	return name + "_" + suffix
}
func firstExecutionError(err error, fallback string) error {
	if err != nil {
		return err
	}
	return errors.New(fallback)
}

func promptOrMessage(prompt, message string) string {
	if strings.TrimSpace(message) != "" {
		return message
	}
	return prompt
}

func basicGuardrail(value string) (bool, string) {
	if strings.TrimSpace(value) == "" {
		return true, ""
	}
	lower := strings.ToLower(value)
	for _, phrase := range []string{"ignore previous instructions", "ignore all instructions", "reveal your system prompt", "jailbreak"} {
		if strings.Contains(lower, phrase) {
			return false, "jailbreak"
		}
	}
	if emailPattern.MatchString(strings.TrimSpace(value)) || regexp.MustCompile(`\b(?:\+?\d[\d\s().-]{8,}\d)\b`).MatchString(value) {
		return false, "pii"
	}
	return true, ""
}

var workflowPIIPatterns = []struct {
	kind    string
	pattern *regexp.Regexp
}{
	{"email", regexp.MustCompile(`\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b`)},
	{"phone", regexp.MustCompile(`\b(?:\+?1[-.]?)?\(?[0-9]{3}\)?[-. ]?[0-9]{3}[-. ]?[0-9]{4}\b`)},
	{"ssn", regexp.MustCompile(`\b\d{3}-\d{2}-\d{4}\b`)},
	{"credit_card", regexp.MustCompile(`\b\d{4}[-\s]?\d{4}[-\s]?\d{4}[-\s]?\d{4}\b`)},
	{"ip_address", regexp.MustCompile(`\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b`)},
	{"date_of_birth", regexp.MustCompile(`\b(?:0?[1-9]|1[0-2])[/-](?:0?[1-9]|[12][0-9]|3[01])[/-](?:19|20)\d{2}\b`)},
}

func evaluateWorkflowGuardrails(text string, config map[string]any) (bool, []map[string]any, string) {
	enabled := workflowGuardrailTypes(config)
	results := make([]map[string]any, 0, len(enabled))
	passed := true
	piiAction := strings.ToLower(configStringDefault(config, "pii_action", "block"))
	for _, kind := range enabled {
		switch kind {
		case "pii":
			violations := make([]string, 0)
			redacted := text
			for _, candidate := range workflowPIIPatterns {
				for _, match := range candidate.pattern.FindAllStringIndex(text, -1) {
					value := text[match[0]:match[1]]
					violations = append(violations, fmt.Sprintf("%s at position %d (length %d)", candidate.kind, match[0], len(value)))
					if piiAction == "redact" {
						redacted = strings.ReplaceAll(redacted, value, "["+strings.ToUpper(candidate.kind)+"_REDACTED]")
					}
				}
			}
			ok := len(violations) == 0
			if !ok {
				passed = false
			}
			entry := map[string]any{"passed": ok, "guardrail_type": "pii", "violations": violations, "confidence": float64(0)}
			if !ok {
				entry["confidence"] = float64(1)
			}
			if piiAction == "redact" {
				entry["redacted_text"] = redacted
			} else {
				entry["redacted_text"] = nil
			}
			results = append(results, entry)
		case "jailbreak":
			ok, reason := basicGuardrail(text)
			if reason != "jailbreak" {
				ok = true
			}
			if !ok {
				passed = false
			}
			violations := []string{}
			if !ok {
				violations = append(violations, "Potential jailbreak attempt detected")
			}
			confidence := float64(0)
			if !ok {
				confidence = 1
			}
			results = append(results, map[string]any{"passed": ok, "guardrail_type": "jailbreak", "violations": violations, "redacted_text": nil, "confidence": confidence})
		}
	}
	if passed {
		return true, results, "Your message has been processed successfully."
	}
	for _, entry := range results {
		if entry["guardrail_type"] == "pii" && entry["passed"] == false {
			return false, results, "I noticed your message contains sensitive personal information. For your privacy and security, please avoid sharing personal details like email addresses, phone numbers, or other identifying information."
		}
	}
	return false, results, "I'm designed to help you with legitimate questions and tasks. I can't process requests that ask me to ignore my guidelines or behave in ways I'm not designed for. How else can I assist you?"
}

func workflowGuardrailTypes(config map[string]any) []string {
	values, ok := config["enabled_guardrails"]
	if !ok {
		return []string{"pii", "jailbreak"}
	}
	result := make([]string, 0, 2)
	switch typed := values.(type) {
	case []any:
		for _, value := range typed {
			if kind := strings.ToLower(strings.TrimSpace(fmt.Sprint(value))); kind == "pii" || kind == "jailbreak" {
				result = append(result, kind)
			}
		}
	case []string:
		for _, value := range typed {
			if kind := strings.ToLower(strings.TrimSpace(value)); kind == "pii" || kind == "jailbreak" {
				result = append(result, kind)
			}
		}
	}
	return result
}

func guardrailConnection(connections []Connection, passed bool) *Connection {
	wanted := "fail"
	if passed {
		wanted = "pass"
	}
	for index := range connections {
		if strings.EqualFold(pointerString(connections[index].Label), wanted) || strings.EqualFold(pointerString(connections[index].Condition), wanted) {
			return &connections[index]
		}
	}
	if !passed {
		return nil
	}
	return firstConnection(connections)
}

func selectCondition(connections []Connection, expression string, state map[string]any) *Connection {
	matched := evaluateCondition(expression, state)
	for i := range connections {
		label := strings.ToLower(strings.TrimSpace(pointerString(connections[i].Label)))
		condition := strings.ToLower(strings.TrimSpace(pointerString(connections[i].Condition)))
		if (matched && (label == "true" || condition == "true")) || (!matched && (label == "false" || condition == "false")) {
			return &connections[i]
		}
	}
	return firstConnection(connections)
}

func pointerString(value *string) string {
	if value == nil {
		return ""
	}
	return *value
}

func evaluateCondition(expression string, state map[string]any) bool {
	expression = strings.TrimSpace(expression)
	for _, op := range []string{"===", "!==", ">=", "<=", "==", "!=", ">", "<", "contains"} {
		if parts := strings.SplitN(expression, op, 2); len(parts) == 2 {
			left, right := strings.Trim(strings.TrimSpace(parts[0]), "'\""), strings.Trim(strings.TrimSpace(parts[1]), "'\"")
			if value := interpolate("{{"+left+"}}", state); value != "" {
				left = value
			}
			switch op {
			case "contains":
				return strings.Contains(left, right)
			case "==", "===":
				return left == right
			case "!=", "!==":
				return left != right
			default:
				l, lErr := strconv.ParseFloat(left, 64)
				r, rErr := strconv.ParseFloat(right, 64)
				if lErr != nil || rErr != nil {
					return false
				}
				if op == ">" {
					return l > r
				}
				if op == "<" {
					return l < r
				}
				if op == ">=" {
					return l >= r
				}
				return l <= r
			}
		}
	}
	return strings.EqualFold(expression, "true")
}
